#
# Home Assistant Automation Blueprint
#
# Synchronize on/off and color attribute states on multiple 3 lights
#
# Revision 0.1.1
# Modified by Redbull Asassin, Sept 10, 2021
#

blueprint:
  name: Light Bonding - Triple
  description: Bind 3 light entities together with brightness synch 
  domain: automation
  input:
    light_1:
      name: Light 1
      selector:
        entity:
          domain: light

    light_2:
      name: Light 2
      selector:
        entity:
          domain: light

    light_3:
      name: Light 3
      selector:
        entity:
          domain: light

trigger:
- entity_id:
  - !input light_1
  - !input light_2
  - !input light_3
  platform: state

action:
- entity_id:
  - !input light_1
  - !input light_2
  - !input light_3
  service: '{% if trigger.to_state.state == "on" %} light.turn_on {% elif trigger.to_state.state == "off" %} light.turn_off {% endif %}'
- entity_id:
  - !input light_1
  - !input light_2
  - !input light_3
  service: light.turn_on
  data:
    brightness: '{{ trigger.to_state.attributes.brightness }}'
#  condition: state
#  state: 'on'
#- service: light.turn_on
#  data:
#    brightness: '{{ trigger.to_state.attributes.brightness }}'
#  entity_id:
#    - !input light_1
#    - !input light_2
#    - !input light_3
