#
# Home Assistant Automation Blueprint
#
# Synchronize on/off and color attribute states on multiple 3 lights
#
# Revision 0.1
# Modified by Redbull Asassin, Aug 19, 2021
#

blueprint:
  name: Triple Light Bonding with Brightness & Color Sync
  description: Bind 3 light entities together Synchronize state and attributes
  domain: automation
  input:
    light_1:
      name: Light 1
      selector:
        entity:
          domain: light

    light_2:
      name: Light 2
      selector:
        entity:
          domain: light

    light_3:
      name: Light 3
      selector:
        entity:
          domain: light

trigger:
- entity_id:
  - !input light_1
  - !input light_2
  - !input light_3
  platform: state

action:
- entity_id:
  - !input light_1
  - !input light_2
  - !input light_3
  service: '{% if trigger.to_state.state == "on" %} light.turn_on {% elif trigger.to_state.state == "off" %} light.turn_off {% endif %}'
- entity_id:
  - !input light_1
  - !input light_2
  - !input light_3
  condition: state
  state: 'on'
- service: light.turn_on
  data:
    supported_color_modes: '{{ trigger.to_state.attributes.supported_color_modes }}'
    brightness: '{{ trigger.to_state.attributes.brightness }}'
    color_mode: '{{ trigger.to_state.attributes.color_mode }}'
    hs_color: '{{ trigger.to_state.attributes.hs_color }}'
    rgb_color: '{{ trigger.to_state.attributes.rgb_color }}'
    xy_color: '{{ trigger.to_state.attributes.xy_color }}'
    color_temp: '{{ trigger.to_state.attributes.color_temp }}'
  entity_id:
    - !input light_1
    - !input light_2
    - !input light_3
